services:
  sample-book-app-dev:
    build: .
    image: vkoposovs/sample-book-app
    container_name: sample-book-app-dev
    ports:
      - 4000:1050
    networks:
      - sample-book-app-compose-network
  sample-book-app-stg:
    build: .
    image: vkoposovs/sample-book-app
    container_name: sample-book-app-stg
    ports:
      - 4001:1050
    networks:
      - sample-book-app-compose-network
  sample-book-app-prd:
    build: .
    image: vkoposovs/sample-book-app
    container_name: sample-book-app-prd
    ports:
      - 4002:1050
    networks:
      - sample-book-app-compose-network

networks:
  sample-book-app-compose-network:
    name: sample-book-app-compose-network